version: '3.8'

services:
  rutube-downloader:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/arm64
    image: rutube-downloader:latest
    container_name: rutube-downloader
    ports:
      - "8000:8000"
    env_file:
      - .env  # Загружает переменные из .env файла
    #environment:
      # Можно переопределить или добавить переменные здесь
      # PYTHONUNBUFFERED: 1
    #volumes:
      # Опционально: монтируем директорию для сохранения файлов
      # - ./downloads:/app/downloads
    restart: unless-stopped

